name: 🔎 Search
description: Search all xkcd comics by concept, joke, or meaning.
title: "Search"
labels: ["xkcd-search"]
body:
  - type: markdown
    attributes:
      value: |
        ### Search all XKCDs
        Once you open the issue, track your issue. The search results should arrive within a minute.
        Note: you do not need to rename the title.
  - type: input
    id: query
    attributes:
      label: What are you looking for?
      placeholder: how a mother deletes a school student list
    validations:
      required: true
