name: 🔎 Search
description: Search all xkcd comics by concept, joke, or meaning.
title: "Search"
labels: ["xkcd-search"]
body:
  - type: markdown
    attributes:
      value: |
        ### Search all XKCDs
        Once you open the issue, please wait. Search results should arrive shortly.
