name: XKCD

on:
  schedule:
    - cron: '5 12 * * 1,3,5'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch-comic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create img directory
        run: mkdir -p img

      - name: Fetch and download xkcd
        id: xkcd
        run: |
          RESPONSE=$(curl -s https://xkcd.com/info.0.json)
          IMG_URL=$(echo "$RESPONSE" | jq -r '.img')
          ALT_TEXT=$(echo "$RESPONSE" | jq -r '.alt')
          
          curl -s -o img/xkcd.png "$IMG_URL"
          echo "$ALT_TEXT" > img/xkcd_alt.txt

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          git add img/xkcd.png img/xkcd_alt.txt
          git diff-index --quiet HEAD || (git commit -m "Automated update: latest xkcd.png and alt text" && git push)
